### ISSUE TITLE
Dangerous download form mac release

### ISSUE THREAD

**Issue by Ridermansb** [kilpkonn/gtm-enhanced#69]
**Describe the bug**

**To Reproduce**
1. Go to release
2. Try download `gtm-core-macOS.zip`

**Expected behavior**
Download without any warnings

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/725337/122960780-2408b580-d35a-11eb-9e3f-7df899e3a06e.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/725337/122960846-34209500-d35a-11eb-9204-65ba38f6233e.png)

**Comment by kilpkonn** [comment]
Thank you for the issue! Does the notification appear in Mac when using any kind of zip file or only gtm? Not a Mac user so not too familiar with it.

**Comment by Ridermansb** [comment]
only gtm.

**Comment by kilpkonn** [comment]
Please see if the warning also appears when downloading `gtm-core-macOS` from here: https://github.com/DEVELOPEST/gtm-core/actions/runs/968277130.
I've removed executable permissions from `gtm` file inside zip from that build so I'd hope no warning but it needs to be tested on mac as well.
